name: Run tests

on:
  pull_request:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: s4u/maven-settings-action@v3.0.0

      - name: Run tests
        run: mvn test
