name: Run tests

on:
  pull_request:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven
        uses: s4u/maven-settings-action@v3.0.0

      - name: Run tests
        run: mvn test
        env:
          FUNCTIONAL_TESTING: false
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          "okta.oauth2.issuer": https://${{ secrets.OKTA_OAUTH2_ISSUER }}/
          "okta.oauth2.audience": ${{ secrets.OKTA_OAUTH2_AUDIENCE }}
